// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WellN_M2_AgenciaViagens.Data;

#nullable disable

namespace WellN_M2_AgenciaViagens.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    [Migration("20220103232717_Recode-Agencia-Trabalho2")]
    partial class RecodeAgenciaTrabalho2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WellN_M2_AgenciaViagens.Models.Clientes", b =>
                {
                    b.Property<int>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UID"), 1L, 1);

                    b.Property<int>("SecID")
                        .HasColumnType("int");

                    b.Property<DateTime>("criadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UID");

                    b.HasIndex("SecID");

                    b.ToTable("dbClients");
                });

            modelBuilder.Entity("WellN_M2_AgenciaViagens.Models.Compras", b =>
                {
                    b.Property<int>("SecID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SecID"), 1L, 1);

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("UID")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("plannedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("qtdd")
                        .HasColumnType("int");

                    b.HasKey("SecID");

                    b.ToTable("dbBuyList");
                });

            modelBuilder.Entity("WellN_M2_AgenciaViagens.Models.Pacotes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("SecID")
                        .HasColumnType("int");

                    b.Property<string>("destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("hasAlimentacao")
                        .HasColumnType("bit");

                    b.Property<bool>("hasAviao")
                        .HasColumnType("bit");

                    b.Property<bool>("hasHotel")
                        .HasColumnType("bit");

                    b.Property<bool>("hasNavio")
                        .HasColumnType("bit");

                    b.Property<bool>("hasOnibus")
                        .HasColumnType("bit");

                    b.Property<int>("pessoasContempladas")
                        .HasColumnType("int");

                    b.Property<double>("preco")
                        .HasColumnType("float");

                    b.Property<double?>("precoOriginal")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("SecID");

                    b.ToTable("dbPackages");
                });

            modelBuilder.Entity("WellN_M2_AgenciaViagens.Models.Suporte", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketID"), 1L, 1);

                    b.Property<int>("SecID")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TicketID");

                    b.HasIndex("SecID");

                    b.ToTable("Suporte");
                });

            modelBuilder.Entity("WellN_M2_AgenciaViagens.Models.Clientes", b =>
                {
                    b.HasOne("WellN_M2_AgenciaViagens.Models.Compras", "Compras")
                        .WithMany("ListClientes")
                        .HasForeignKey("SecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compras");
                });

            modelBuilder.Entity("WellN_M2_AgenciaViagens.Models.Pacotes", b =>
                {
                    b.HasOne("WellN_M2_AgenciaViagens.Models.Compras", "Compras")
                        .WithMany("ListPacotes")
                        .HasForeignKey("SecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compras");
                });

            modelBuilder.Entity("WellN_M2_AgenciaViagens.Models.Suporte", b =>
                {
                    b.HasOne("WellN_M2_AgenciaViagens.Models.Compras", "Compras")
                        .WithMany("ListSuporte")
                        .HasForeignKey("SecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compras");
                });

            modelBuilder.Entity("WellN_M2_AgenciaViagens.Models.Compras", b =>
                {
                    b.Navigation("ListClientes");

                    b.Navigation("ListPacotes");

                    b.Navigation("ListSuporte");
                });
#pragma warning restore 612, 618
        }
    }
}
